macro_rules! invoke_handler {
    () => {
        tauri::generate_handler![
            // service
            crate::commands::service::service_start,
            crate::commands::service::service_stop,
            crate::commands::service::service_initialize,
            crate::commands::service::service_rpc_token,
            crate::commands::directObservation::service_observation_status,
            crate::commands::directObservation::service_observation_start,
            crate::commands::directObservation::service_observation_stop,
            crate::commands::sessionRouting::service_session_routing_status,
            crate::commands::sessionRouting::service_session_routing_set_enabled,
            crate::commands::sessionRouting::service_session_routing_set_account_enabled,
            crate::commands::startup::service_startup_snapshot,
            // request log
            crate::commands::requestlog::service_requestlog_detail,
            crate::commands::requestlog::service_requestlog_list,
            crate::commands::requestlog::service_requestlog_list_with_summary,
            crate::commands::requestlog::service_requestlog_summary,
            crate::commands::requestlog::service_requestlog_cost_breakdown,
            crate::commands::requestlog::service_requestlog_clear,
            crate::commands::requestlog::service_requestlog_today_summary,
            // plugin
            // settings
            crate::commands::settings::proxy_profiles::service_system_proxy_list,
            crate::commands::settings::proxy_profiles::service_system_proxy_test_presets,
            crate::commands::settings::proxy_profiles::service_system_proxy_create,
            crate::commands::settings::proxy_profiles::service_system_proxy_update,
            crate::commands::settings::proxy_profiles::service_system_proxy_delete,
            crate::commands::settings::proxy_profiles::service_system_proxy_test,
            crate::commands::settings::proxy_profiles::service_system_proxy_test_latency,
            crate::commands::settings::proxy_profiles::service_system_proxy_speed_test,
            crate::commands::settings::proxy_profiles::service_system_proxy_cloudflare_speed_test,
            crate::commands::settings::proxy_profiles::service_system_proxy_test_job,
            crate::commands::settings::proxy_profiles::service_system_proxy_cancel_test,
            crate::commands::settings::proxy_profiles::service_system_proxy_speed_test_history,
            crate::commands::settings::proxy_profiles::service_system_proxy_latency_test_history,
            crate::commands::settings::proxy_profiles::service_system_proxy_diagnostics_history,
            crate::commands::settings::ui::app_settings_get,
            crate::commands::settings::ui::app_settings_set,
            crate::commands::settings::ui::app_close_to_tray_on_close_get,
            crate::commands::settings::ui::app_close_to_tray_on_close_set,
            // desktop diagnostics
            crate::commands::diagnostics::app_diagnostics_settings_get,
            crate::commands::diagnostics::app_diagnostics_settings_set,
            crate::commands::diagnostics::app_diagnostics_open_logs_dir,
            // login
            crate::commands::login::service_login_start,
            crate::commands::login::service_login_status,
            crate::commands::login::service_login_cancel,
            crate::commands::login::service_login_complete,
            crate::commands::login::service_login_chatgpt_auth_tokens,
            crate::commands::login::service_account_read,
            crate::commands::login::service_account_logout,
            crate::commands::login::service_chatgpt_auth_tokens_refresh,
            crate::commands::login::service_chatgpt_auth_tokens_refresh_all,
            // account
            crate::commands::account::local::local_account_delete,
            crate::commands::account::remote::service_account_list,
            crate::commands::account::remote::service_account_delete,
            crate::commands::account::remote::service_account_delete_many,
            crate::commands::account::remote::service_account_delete_unavailable_free,
            crate::commands::account::remote::service_account_delete_by_statuses,
            crate::commands::account::remote::service_account_update,
            crate::commands::account::remote::service_account_update_sorts,
            crate::commands::account::remote::service_account_warmup,
            crate::commands::account::remote::service_account_fetch_models,
            crate::commands::account::remote::service_account_associate_models,
            crate::commands::account::remote::service_account_test_start,
            crate::commands::account::remote::service_account_test_cancel,
            crate::commands::account::remote::service_account_proxy_get,
            crate::commands::account::remote::service_account_proxy_set,
            crate::commands::account::remote::service_account_proxy_clear,
            crate::commands::account::remote::service_account_proxy_test,
            crate::commands::account::remote::service_account_proxy_latency_test,
            crate::commands::account::remote::service_account_proxy_speed_test,
            crate::commands::account::remote::service_account_proxy_cloudflare_speed_test,
            crate::commands::account::remote::service_account_proxy_test_job,
            crate::commands::account::remote::service_account_proxy_cancel_test,
            crate::commands::account::remote::service_account_proxy_speed_test_history,
            crate::commands::account::remote::service_account_proxy_latency_test_history,
            crate::commands::account::remote::service_account_proxy_diagnostics_history,
            crate::commands::account::transfer::service_account_import,
            crate::commands::account::transfer::service_account_import_by_directory,
            crate::commands::account::transfer::service_account_import_by_file,
            crate::commands::account::transfer::service_account_export_by_account_files,
            // account manager
            // usage
            crate::commands::usage::service_usage_read,
            crate::commands::usage::service_usage_list,
            crate::commands::usage::service_usage_aggregate,
            crate::commands::usage::service_usage_refresh,
            crate::commands::usage::service_usage_reset_credits,
            crate::commands::usage::service_usage_reset_credit_consume,
            // api key
            // system
            crate::commands::system::open_in_browser,
            crate::commands::system::open_external_url,
            crate::commands::system::open_in_file_manager,
            crate::commands::system::app_window_unsaved_draft_sections_set,
            crate::commands::system::app_show_main_window,
            // updater
            crate::commands::updater::app_update_check,
            crate::commands::updater::app_update_prepare,
            crate::commands::updater::app_update_apply_portable,
            crate::commands::updater::app_update_launch_installer,
            crate::commands::updater::app_update_status,
            crate::commands::updater::app_update_open_logs_dir
        ]
    };
}

pub(crate) use invoke_handler;
